#https://strimzi.io/docs/operators/latest/using.html#type-KafkaMirrorMaker2-reference
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: mirror-maker2
spec:
  version: 2.8.0
  template:
    pod:
      metadata:
        annotations:
          prometheus.io/port: '9404'
          prometheus.io/scrape: 'true'
  logging:
    type: inline
    loggers:
      connect.root.logger.level: "INFO"